# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	 config.vm.define "docker" do |d|
		d.vm.box = "ubuntu/xenial64"
		
		d.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", 4096]
			vb.customize ["modifyvm", :id, "--cpus", 2]
		end
		
		#przekierowanie portu
		config.vm.network "forwarded_port", guest:8000, host:8000
		
		config.vm.synced_folder ".", "/home/vagrant/shared"
		#config.ssh.username = "vagrant"
		#config.ssh.password = "vagrant"
		
		config.vm.provision "shell", inline: <<-SHELL
			sudo apt-get update
			sudo apt-get upgrade -y
			sudo apt-get install apt-transport-https ca-certificates curl -y
			sudo apt-get install software-properties-common -y
			curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
			sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
			sudo apt-get update
			sudo apt-get install docker-ce -y	
			
			#installing docker-compose
			sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
			sudo chmod +x /usr/local/bin/docker-compose

			sudo mkdir /home/docker
			sudo cp /home/vagrant/shared/docker-compose.yml /home/docker/docker-compose.yml
			cd /home/docker
			#sudo docker-compose up -d
			
			sudo docker swarm init
			sudo docker stack deploy -c docker-compose.yml prod

		SHELL
		end
end
